t8ntool: get back the baseFee setter for London
Get back the code removed in fb84a68095e31b2998316a366faffd88b3445147.
If it's London, then BaseFee should still be calculated based on the
parent's fee. If it's NeoXBurn, then just ensure that BaseFee is set in
the config (this check is already present in the applyNeoXBurnChecks.

Fix the following test:
```
--- FAIL: TestT8n (0.39s)
    t8n_test.go:299: args: t8n --output.body "" --output.result stdout --output.alloc stdout --input.alloc ./testdata/1/alloc.json --input.txs ./testdata/1/txs.json --input.env ./testdata/1/env.json --state.fork Frontier+1346
    test_cmd.go:261: (stderr:1) ERROR(3): failed constructing chain configuration: syntax error, invalid eip number 1346
    t8n_test.go:299: args: t8n --output.body "" --output.result stdout --output.alloc stdout --input.alloc ./testdata/1/alloc.json --input.txs ./testdata/1/txs.json --input.env ./testdata/1/env.json --state.fork Byzantium
    test_cmd.go:261: (stderr:6) INFO [06-25|16:52:13.126] rejected tx                              index=1 hash=0557ba..18d673 from=0x8A8eAFb1cf62BfBeb1741769DAE1a9dd47996192 error="nonce too low: address 0x8A8eAFb1cf62BfBeb1741769DAE1a9dd47996192, tx: 0 state: 1"
    test_cmd.go:261: (stderr:6) INFO [06-25|16:52:13.126] Trie dumping started                     root=84208a..ae4e13
    test_cmd.go:261: (stderr:6) INFO [06-25|16:52:13.126] Trie dumping complete                    accounts=3 elapsed="60.108µs"
    t8n_test.go:299: args: t8n --output.body "" --output.result stdout --output.alloc stdout --input.alloc ./testdata/3/alloc.json --input.txs ./testdata/3/txs.json --input.env ./testdata/3/env.json --state.fork Berlin
    test_cmd.go:261: (stderr:9) INFO [06-25|16:52:13.152] Trie dumping started                     root=b7341d..857ea1
    test_cmd.go:261: (stderr:9) INFO [06-25|16:52:13.153] Trie dumping complete                    accounts=3 elapsed="90.49µs"
    t8n_test.go:299: args: t8n --output.body "" --output.result stdout --output.alloc stdout --input.alloc ./testdata/4/alloc.json --input.txs ./testdata/4/txs.json --input.env ./testdata/4/env.json --state.fork Berlin
    test_cmd.go:261: (stderr:12) ERROR(4): getHash(3) invoked, blockhash for that block not provided
    t8n_test.go:299: args: t8n --output.body "" --output.result stdout --output.alloc stdout --input.alloc ./testdata/5/alloc.json --input.txs ./testdata/5/txs.json --input.env ./testdata/5/env.json --state.fork Byzantium --state.reward 0x80
    test_cmd.go:261: (stderr:15) INFO [06-25|16:52:13.205] Trie dumping started                     root=a7312a..c1f393
    test_cmd.go:261: (stderr:15) INFO [06-25|16:52:13.205] Trie dumping complete                    accounts=3 elapsed="70.846µs"
    t8n_test.go:299: args: t8n --output.body stdout --output.result "" --output.alloc "" --input.alloc ./testdata/13/alloc.json --input.txs ./testdata/13/txs.json --input.env ./testdata/13/env.json --state.fork London
    test_cmd.go:261: (stderr:16) INFO [06-25|16:52:13.234] Trie dumping started                     root=e4b924..6aef61
    test_cmd.go:261: (stderr:16) INFO [06-25|16:52:13.234] Trie dumping complete                    accounts=3 elapsed="104.878µs"
    t8n_test.go:299: args: t8n --output.body "" --output.result stdout --output.alloc "" --input.alloc ./testdata/13/alloc.json --input.txs ./testdata/13/signed_txs.rlp --input.env ./testdata/13/env.json --state.fork London
    test_cmd.go:261: (stderr:18) INFO [06-25|16:52:13.256] Trie dumping started                     root=e4b924..6aef61
    test_cmd.go:261: (stderr:18) INFO [06-25|16:52:13.256] Trie dumping complete                    accounts=3 elapsed="61.682µs"
    t8n_test.go:299: args: t8n --output.body "" --output.result stdout --output.alloc "" --input.alloc ./testdata/14/alloc.json --input.txs ./testdata/14/txs.json --input.env ./testdata/14/env.json --state.fork London
    test_cmd.go:261: (stderr:19) INFO [06-25|16:52:13.277] Trie dumping started                     root=6f0588..7f4bdc
    test_cmd.go:261: (stderr:19) INFO [06-25|16:52:13.277] Trie dumping complete                    accounts=2 elapsed="65.13µs"
    t8n_test.go:299: args: t8n --output.body "" --output.result stdout --output.alloc "" --input.alloc ./testdata/14/alloc.json --input.txs ./testdata/14/txs.json --input.env ./testdata/14/env.uncles.json --state.fork London
    test_cmd.go:261: (stderr:20) INFO [06-25|16:52:13.298] Trie dumping started                     root=6f0588..7f4bdc
    test_cmd.go:261: (stderr:20) INFO [06-25|16:52:13.298] Trie dumping complete                    accounts=2 elapsed="54.479µs"
    t8n_test.go:299: args: t8n --output.body "" --output.result stdout --output.alloc "" --input.alloc ./testdata/14/alloc.json --input.txs ./testdata/14/txs.json --input.env ./testdata/14/env.uncles.json --state.fork Berlin
    test_cmd.go:261: (stderr:21) INFO [06-25|16:52:13.318] Trie dumping started                     root=6f0588..7f4bdc
    test_cmd.go:261: (stderr:21) INFO [06-25|16:52:13.318] Trie dumping complete                    accounts=2 elapsed="53.961µs"
    t8n_test.go:299: args: t8n --output.body "" --output.result stdout --output.alloc "" --input.alloc ./testdata/19/alloc.json --input.txs ./testdata/19/txs.json --input.env ./testdata/19/env.json --state.fork London
    test_cmd.go:261: (stderr:22) INFO [06-25|16:52:13.338] Trie dumping started                     root=6f0588..7f4bdc
    test_cmd.go:261: (stderr:22) INFO [06-25|16:52:13.338] Trie dumping complete                    accounts=2 elapsed="62.368µs"
    t8n_test.go:299: args: t8n --output.body "" --output.result stdout --output.alloc "" --input.alloc ./testdata/19/alloc.json --input.txs ./testdata/19/txs.json --input.env ./testdata/19/env.json --state.fork ArrowGlacier
    test_cmd.go:261: (stderr:23) INFO [06-25|16:52:13.359] Trie dumping started                     root=6f0588..7f4bdc
    test_cmd.go:261: (stderr:23) INFO [06-25|16:52:13.359] Trie dumping complete                    accounts=2 elapsed="62.569µs"
    t8n_test.go:299: args: t8n --output.body "" --output.result stdout --output.alloc "" --input.alloc ./testdata/19/alloc.json --input.txs ./testdata/19/txs.json --input.env ./testdata/19/env.json --state.fork GrayGlacier
    test_cmd.go:261: (stderr:24) INFO [06-25|16:52:13.379] Trie dumping started                     root=6f0588..7f4bdc
    test_cmd.go:261: (stderr:24) INFO [06-25|16:52:13.379] Trie dumping complete                    accounts=2 elapsed="66.893µs"
    t8n_test.go:299: args: t8n --output.body "" --output.result stdout --output.alloc "" --input.alloc ./testdata/23/alloc.json --input.txs ./testdata/23/txs.json --input.env ./testdata/23/env.json --state.fork Berlin
    test_cmd.go:261: (stderr:25) INFO [06-25|16:52:13.401] Trie dumping started                     root=653343..95154d
    test_cmd.go:261: (stderr:25) INFO [06-25|16:52:13.401] Trie dumping complete                    accounts=3 elapsed="56.934µs"
    t8n_test.go:299: args: t8n --output.body "" --output.result stdout --output.alloc stdout --input.alloc ./testdata/24/alloc.json --input.txs ./testdata/24/txs.json --input.env ./testdata/24/env.json --state.fork Merge
    test_cmd.go:261: (stderr:26) INFO [06-25|16:52:13.421] Trie dumping started                     root=9e4224..043c15
    test_cmd.go:261: (stderr:26) INFO [06-25|16:52:13.421] Trie dumping complete                    accounts=3 elapsed="65.042µs"
    t8n_test.go:299: args: t8n --output.body "" --output.result "" --output.alloc "" --input.alloc ./testdata/24/alloc.json --input.txs ./testdata/24/txs.json --input.env ./testdata/24/env-missingrandom.json --state.fork Merge
    test_cmd.go:261: (stderr:27) ERROR(3): post-merge requires currentRandom to be defined in env
    t8n_test.go:299: args: t8n --output.body "" --output.result stdout --output.alloc stdout --input.alloc ./testdata/25/alloc.json --input.txs ./testdata/25/txs.json --input.env ./testdata/25/env.json --state.fork Merge
    test_cmd.go:261: (stderr:28) panic: runtime error: invalid memory address or nil pointer dereference
    test_cmd.go:261: (stderr:28) [signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x5f5dbb]
    test_cmd.go:261: (stderr:28) goroutine 1 [running]:
    test_cmd.go:261: (stderr:28) math/big.(*Int).Cmp(0xc00057da40?, 0x0?)
    test_cmd.go:261: (stderr:28) 	/usr/local/go/src/math/big/int.go:381 +0x1b
    test_cmd.go:261: (stderr:28) github.com/ethereum/go-ethereum/core.(*StateTransition).preCheck(0xc00028ebb0)
    test_cmd.go:261: (stderr:28) 	/home/anna/Documents/GitProjects/bane-labs/go-ethereum/core/state_transition.go:323 +0x6f2
    test_cmd.go:261: (stderr:28) github.com/ethereum/go-ethereum/core.(*StateTransition).TransitionDb(0xc00028ebb0)
    test_cmd.go:261: (stderr:28) 	/home/anna/Documents/GitProjects/bane-labs/go-ethereum/core/state_transition.go:396 +0x51
    test_cmd.go:261: (stderr:28) github.com/ethereum/go-ethereum/core.ApplyMessage(0x152ada8?, 0x152adb0?, 0xc000579158?)
    test_cmd.go:261: (stderr:28) 	/home/anna/Documents/GitProjects/bane-labs/go-ethereum/core/state_transition.go:184 +0x57
    test_cmd.go:261: (stderr:28) github.com/ethereum/go-ethereum/cmd/evm/internal/t8ntool.(*Prestate).Apply(0xc0003ea2d0, {{0x0, 0x0}, 0x0, 0x0, {0x0, 0x0, 0x0}}, 0xc0004ad6c0, {0x1694ef8, ...}, ...)
    test_cmd.go:261: (stderr:28) 	/home/anna/Documents/GitProjects/bane-labs/go-ethereum/cmd/evm/internal/t8ntool/execution.go:243 +0x17cf
    test_cmd.go:261: (stderr:28) github.com/ethereum/go-ethereum/cmd/evm/internal/t8ntool.Transition(0xc000267300)
    test_cmd.go:261: (stderr:28) 	/home/anna/Documents/GitProjects/bane-labs/go-ethereum/cmd/evm/internal/t8ntool/transition.go:188 +0xb65
    test_cmd.go:261: (stderr:28) github.com/ethereum/go-ethereum/internal/flags.MigrateGlobalFlags.func2.1(0xc000267300)
    test_cmd.go:261: (stderr:28) 	/home/anna/Documents/GitProjects/bane-labs/go-ethereum/internal/flags/helpers.go:100 +0x34
    test_cmd.go:261: (stderr:28) github.com/urfave/cli/v2.(*Command).Run(0x1f59480, 0xc000267300, {0xc0003ea1e0, 0xf, 0xf})
    test_cmd.go:261: (stderr:28) 	/home/anna/go/pkg/mod/github.com/urfave/cli/v2@v2.25.7/command.go:274 +0x93f
    test_cmd.go:261: (stderr:28) github.com/urfave/cli/v2.(*Command).Run(0xc00044eb00, 0xc000266040, {0xc000040100, 0x10, 0x10})
    test_cmd.go:261: (stderr:28) 	/home/anna/go/pkg/mod/github.com/urfave/cli/v2@v2.25.7/command.go:267 +0xb7d
    test_cmd.go:261: (stderr:28) github.com/urfave/cli/v2.(*App).RunContext(
    test_cmd.go:261: (stderr:28) 0xc00016c5a0, {0x169aad0, 0x2166400}, {0xc000040100, 0x10, 0x10})
    test_cmd.go:261: (stderr:28) 	/home/anna/go/pkg/mod/github.com/urfave/cli/v2@v2.25.7/app.go:332 +0x566
    test_cmd.go:261: (stderr:28) github.com/urfave/cli/v2.(*App).Run(...)
    test_cmd.go:261: (stderr:28) 	/home/anna/go/pkg/mod/github.com/urfave/cli/v2@v2.25.7/app.go:309
    test_cmd.go:261: (stderr:28) github.com/ethereum/go-ethereum/cmd/evm.TestMain.func1()
    test_cmd.go:261: (stderr:28) 	/home/anna/Documents/GitProjects/bane-labs/go-ethereum/cmd/evm/t8n_test.go:35 +0x45
    test_cmd.go:261: (stderr:28) github.com/ethereum/go-ethereum/internal/reexec.Init(...)
    test_cmd.go:261: (stderr:28) 	/home/anna/Documents/GitProjects/bane-labs/go-ethereum/internal/reexec/reexec.go:31
    test_cmd.go:261: (stderr:28) github.com/ethereum/go-ethereum/cmd/evm.TestMain(0xc00043e280)
    test_cmd.go:261: (stderr:28) 	/home/anna/Documents/GitProjects/bane-labs/go-ethereum/cmd/evm/t8n_test.go:42 +0x67
    test_cmd.go:261: (stderr:28) main.main()
    test_cmd.go:261: (stderr:28) 	_testmain.go:53 +0x195
    t8n_test.go:312: test 16, file ./testdata/25/exp.json: json parsing failed: unexpected end of JSON input
FAIL
FAIL	github.com/ethereum/go-ethereum/cmd/evm	0.413s

```

Signed-off-by: Anna Shaleva <shaleva.ann@nspcc.ru>