core: fix filing test after v1.13.15 merge
msg.GasTipCap is nil, but I'm not sure why, it shouldn't be like that
in the real network.

```
--- FAIL: TestExecutionSpecState (0.01s)
    --- FAIL: TestExecutionSpecState/berlin/eip2930_access_list/acl/access_list.json (0.00s)
        --- FAIL: TestExecutionSpecState/berlin/eip2930_access_list/acl/access_list.json/tests/berlin/eip2930_access_list/test_acl.py::test_access_list[fork_Berlin-state_test] (0.00s)
            --- FAIL: TestExecutionSpecState/berlin/eip2930_access_list/acl/access_list.json/tests/berlin/eip2930_access_list/test_acl.py::test_access_list[fork_Berlin-state_test]/Berlin/0/hash/trie (0.00s)
panic: runtime error: invalid memory address or nil pointer dereference [recovered]
	panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x5e2ad8]

goroutine 78973 [running]:
testing.tRunner.func1.2({0xd79340, 0x162a1b0})
	/usr/local/go/src/testing/testing.go:1631 +0x24a
testing.tRunner.func1()
	/usr/local/go/src/testing/testing.go:1634 +0x377
panic({0xd79340?, 0x162a1b0?})
	/usr/local/go/src/runtime/panic.go:770 +0x132
math/big.(*Int).Cmp(0x0?, 0x0?)
	/usr/local/go/src/math/big/int.go:381 +0x18
github.com/ethereum/go-ethereum/core.(*StateTransition).preCheck(0xc001317628)
	/home/anna/Documents/GitProjects/bane-labs/go-ethereum/core/state_transition.go:300 +0x485
github.com/ethereum/go-ethereum/core.(*StateTransition).TransitionDb(0xc001317628)
	/home/anna/Documents/GitProjects/bane-labs/go-ethereum/core/state_transition.go:393 +0x51
github.com/ethereum/go-ethereum/core.ApplyMessage(0x0?, 0xf97800?, 0xf96f28?)
	/home/anna/Documents/GitProjects/bane-labs/go-ethereum/core/state_transition.go:184 +0x57
github.com/ethereum/go-ethereum/tests.(*StateTest).RunNoVerify(0xc0001794a0, {{0xc000353730?, 0xc001142006?}, 0x7dc007fd8a68?}, {{0x0, 0x0}, 0x0, 0x0, {0x0, 0x0, ...}}, ...)
	/home/anna/Documents/GitProjects/bane-labs/go-ethereum/tests/state_test_util.go:301 +0x9e5
github.com/ethereum/go-ethereum/tests.(*StateTest).Run(0xc0001794a0, {{0xc000353730?, 0x6?}, 0x0?}, {{0x0, 0x0}, 0x0, 0x0, {0x0, 0x0, ...}}, ...)
	/home/anna/Documents/GitProjects/bane-labs/go-ethereum/tests/state_test_util.go:198 +0xf7
github.com/ethereum/go-ethereum/tests.execStateTest.func1.1({{0x0, 0x0}, 0x0, 0x0, {0x0, 0x0, 0x0}})
	/home/anna/Documents/GitProjects/bane-labs/go-ethereum/tests/state_test.go:113 +0xef
github.com/ethereum/go-ethereum/tests.withTrace(0xc001129520, 0x4ef00, 0xc001317f18)
	/home/anna/Documents/GitProjects/bane-labs/go-ethereum/tests/state_test.go:167 +0x75
github.com/ethereum/go-ethereum/tests.execStateTest.func1(0xc001129520)
	/home/anna/Documents/GitProjects/bane-labs/go-ethereum/tests/state_test.go:111 +0x12b
testing.tRunner(0xc001129520, 0xc002c0d350)
	/usr/local/go/src/testing/testing.go:1689 +0xfb
created by testing.(*T).Run in goroutine 78972
	/usr/local/go/src/testing/testing.go:1742 +0x390

```

Signed-off-by: Anna Shaleva <shaleva.ann@nspcc.ru>